language: generic
sudo: false
branches:
  only:
    - master
    - develop
before_install:
  - if [ ! -z "$EVM_EMACS" ]; then curl -fsSkL https://raw.github.com/rejeep/evm/master/go > x.sh && source ./x.sh; fi
  - evm install $EVM_EMACS --use --skip
  - evm config path /tmp
  - cp init.test.el init.el
  - INSECURE=1 YES=1 make install
env:
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
script:
  - emacs --version
  - DEBUG=1 make test
